export enum ErrorCode {
  // ===== COMMON =====
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // ===== AUTH =====
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_MISSING = 'AUTH_REFRESH_TOKEN_MISSING',

  // ===== USER =====
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_DUPLICATED = 'USER_EMAIL_DUPLICATED',
  USER_USERNAME_DUPLICATED = 'USER_USERNAME_DUPLICATED',

  // ===== ROLE =====
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_NAME_DUPLICATED = 'ROLE_NAME_DUPLICATED',

  // ===== UPLOAD =====
  UPLOAD_FILE_TOO_LARGE = 'UPLOAD_FILE_TOO_LARGE',
  UPLOAD_INVALID_TYPE = 'UPLOAD_INVALID_TYPE',
  UPLOAD_NO_FILE = 'UPLOAD_NO_FILE',
}
